FROM debian:8

RUN apt-get update

RUN apt-get install -y apache2 apache2-doc apache2-mpm-prefork apache2-utils libexpat1 ssl-cert
RUN apt-get install -y libapache2-mod-php5 php5 php5-common php5-curl php5-dev php5-gd php5-idn php-pear php5-imagick php5-imap php5-json php5-mcrypt php5-memcache php5-mhash php5-mysql php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl

#RUN docker-php-ext-install pdo mysql
#RUN docker-php-ext-install pdo mysqli

RUN a2enmod rewrite

RUN apt-get clean


RUN sed -i "s/display_errors = .*/display_errors = On/" /etc/php5/apache2/php.ini

COPY xdebug.sh /tmp/
RUN sh /tmp/xdebug.sh

COPY virtualhost.conf /etc/apache2/sites-enabled/000-default.conf

EXPOSE 80
EXPOSE 443 

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

